owncast/owncast-admin

package-lock.json, package.json, pages/components/chart.tsx, pages/components/log-table.tsx, pages/components/main-layout.tsx, pages/hardware-info.tsx, pages/viewer-info.tsx
I kept seeing issues drawing the hardware multi-series graph.  So I swapped out the graphing library and this one is fine.
* Replace Recharts with Chartkick.
* Remove all the d3 utils stuff needed for Recharts.
* Remove the chart resize logic tied to window size since it's no longer needed.
=> Replace recharts with Chartkick

pages/viewer-info.tsx
Fixes https://github.com/owncast/owncast/issues/540
=> Implement sorting by "Connected Time"

pages/chat.tsx, styles/chat.scss
Handles https://github.com/owncast/owncast/issues/569
=> Reload chat messages after FETCH_INTERVAL

pages/components/config/edit-server-details.tsx, pages/components/config/form-textfield.tsx
=> Add random streamkey generation and copy key

components/main-layout.tsx
Fixes https://github.com/owncast/owncast/issues/772
=> fix: set thumbnail image to fixed size and fix label color

components/config/video-variant-form.tsx, components/config/video-variants-table.tsx, types/config-section.ts, utils/config-constants.tsx
Closes https://github.com/owncast/owncast/issues/743
=> Support setting a custom name for a stream output variant

components/config/edit-server-details.tsx, types/config-section.ts, utils/config-constants.tsx, utils/server-status-context.tsx
Must be run against https://github.com/owncast/owncast/pull/799 in owncast/owncast.
=> Add server setting to disable chat

components/config/edit-instance-details.tsx, types/config-section.ts, utils/config-constants.tsx, utils/server-status-context.tsx
see https://github.com/owncast/owncast/issues/723
=> implement custom welcome message

components/main-layout.tsx, pages/actions.tsx, types/config-section.ts, utils/apis.ts, utils/config-constants.tsx, utils/server-status-context.tsx
Can add a url, title, description, icon and color for it to display in the frontend UI.
=> Admin support for creating 3rd party external link actions

components/config/edit-instance-details.tsx, styles/globals.scss, utils/config-constants.tsx
This seems to fix it.
See https://github.com/owncast/owncast/issues/854 for details.
=> Changing server url was resetting other updated fields

components/config/edit-social-links.tsx, styles/config-socialhandles.scss
Closes https://github.com/owncast/owncast/issues/845
=> Truncate url and limit width of social content

components/news-feed.tsx, pages/index.tsx, pages/offline-notice.tsx, styles/home.scss, utils/apis.ts
addresses https://github.com/owncast/owncast/issues/865
=> add news feed

pages/offline-notice.tsx, styles/globals.scss
Related to https://github.com/owncast/owncast/issues/861
=> added stream conneciton info box to offline notice

components/config/edit-custom-css.tsx, pages/config-public-details.tsx, styles/config-public-details.scss, types/config-section.ts, utils/config-constants.tsx, utils/server-status-context.tsx
Admin work to address https://github.com/owncast/owncast/issues/718
- The form has been set up to update an endpoint at `api/admin/config/customstyles`.
- The field name that comes back is expected to be `instanceDetails.customStyles`
=> add textarea field for custom css

utils/config-constants.tsx
assuming no change required for gui slider on admin
=> lower min vid rate re issue 989

components/log-table.tsx
tested with stream connect disconnect all good
=> added seconds format for log

pages/_app.tsx, pages/offline-notice.tsx, styles/globals.scss, styles/offline-notice.scss
Like I mentioned in https://github.com/owncast/owncast/issues/1017, the positioning, margins and alignment of the stream info field look a bit different when compared to the rest of the layout. I tried to rework this section and use some css-grid to improve the alignment.
=> rework stream info box in offline notice to conform more with the overall design

components/news-feed.tsx
=> Collapse news content in the admin home page

.eslintrc.js, components/chart.tsx, components/config/edit-custom-css.tsx, components/config/edit-logo.tsx, components/config/edit-social-links.tsx, components/config/edit-tags.tsx, components/config/form-textfield-with-submit.tsx, components/config/social-icons-dropdown.tsx, components/config/video-codec-selector.tsx, components/config/video-variants-table.tsx, components/main-layout.tsx, components/message-visiblity-toggle.tsx, components/news-feed.tsx, package-lock.json, package.json, pages/access-tokens.tsx, pages/actions.tsx, pages/config-chat.tsx, pages/config-video.tsx, pages/offline-notice.tsx, pages/webhooks.tsx, types/config-section.ts
Updates Next to 11.0.1 and fixes a bunch of linter issues. Most significantly, importing issues with chartkick have been resolved.
Replaces #229.
Closes owncast/owncast#1169.
=> Update Next to 11.0.1 (including lint & import fixes)

utils/config-constants.tsx
Fixes https://github.com/owncast/owncast/issues/1320
Hi @gabek, how does this look?
Let me know if this needs any changes.
Thanks
=> change admin directory toggle text

utils/config-constants.tsx
TEXTFIELD_PROPS_SERVER_WELCOME_MESSAGE.maxLength = 2500
Fixes #1595
I didn't find anywhere to add an entry to a changelog. Contributing looks pretty laid-back. Let me know if there is anything else you'd like me to add for this.
I'm not a UI guy, but maybe an expandable text field should go along with this change.
=> Increase Welcome Message maxLength
